apiVersion: v1
kind: Namespace
metadata:
  name: multistate-dev
  labels:
    app.kubernetes.io/name: multistate-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: multistate
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
