# uptimecrew/multistate-config/overlays/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: multistate-staging

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

images:
  - name: uptimecrew/multistate-api
    newName: uptimecrew/multistate-api
    newTag: "0.1.0"

replicas:
  - name: multistate-api
    count: 2

patches:
  - target:
      kind: Namespace
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-1"
  - target:
      kind: ConfigMap
      name: multistate-api-config
    patch: |-
      - op: replace
        path: /data/SPRING_PROFILES_ACTIVE
        value: docker,staging
      - op: add
        path: /data/LOG_LEVEL
        value: INFO
  - target:
      kind: HorizontalPodAutoscaler
      name: multistate-api
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
  - target:
      kind: Ingress
      name: multistate-api
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: multistate.staging.uptimecrew.internal
